"""Inline assets/icons.svg into every page.

The pages can't reference the sprite as an external file: `<use href="...svg#id">`
renders nothing over file:// and is unsupported in Safari. So the sprite is
pasted into each page between marker comments and referenced same-document.

Edit assets/icons.svg, then run this script from the repo root.
"""

import glob
import os
import re

START = "<!-- icon-sprite:start (generated by scripts/sync_icons.py -- edit assets/icons.svg) -->"
END = "<!-- icon-sprite:end -->"


def sprite_markup() -> str:
    raw = open("assets/icons.svg", encoding="utf-8").read()
    body = re.search(r"<svg[^>]*>(.*)</svg>", raw, re.S).group(1)
    body = re.sub(r"<!--.*?-->", "", body, flags=re.S).strip()
    body = "\n".join("      " + ln.strip() for ln in body.split("\n") if ln.strip())
    return (
        f"    {START}\n"
        '    <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false"\n'
        '         style="position:absolute;width:0;height:0;overflow:hidden">\n'
        f"{body}\n"
        "    </svg>\n"
        f"    {END}\n"
    )


def main() -> None:
    block = sprite_markup()
    pages = [f for f in glob.glob("**/*.html", recursive=True)
             if not f.startswith("assets" + os.sep)]
    for f in pages:
        s = open(f, encoding="utf-8").read()
        original = s

        # Point every reference at the same-document symbol.
        s = re.sub(r'href="[^"]*assets/icons\.svg#([\w-]+)"', r'href="#ico-\1"', s)
        s = re.sub(r'href="#ico-ico-', 'href="#ico-', s)

        if START in s:
            s = re.sub(re.escape(START) + r".*?" + re.escape(END) + r"\n",
                       block, s, flags=re.S)
        elif "#ico-" in s:
            s = re.sub(r"(<body[^>]*>\n)", r"\1" + block.replace("\\", "\\\\"), s, count=1)

        if s != original:
            open(f, "w", encoding="utf-8").write(s)
            print("  synced", f)


if __name__ == "__main__":
    main()
